name: learnings
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12.11
  - pandas
  - fastcore
  - nbconvert
  - fastprogress
  - einops
  - accelerate
  - pytorch
  - matplotlib
  - jupyter
  - ipykernel
  - datasets
  - scikit-learn
  - ruff
  - pre-commit
  - pytest
  - pip
  - pip:
    - aiofiles
    - httpx
